dynaconf/dynaconf

- README.md
- dynaconf/utils/boxing.py
- dynaconf/utils/parse_conf.py
- tests/test_utils.py
Suggested by @danilobellini
To disable the automatic envvar casting like `@int 42` now it is possible to do:
```bash
export AUTO_CAST_FOR_DYNACONF=off
```
> Added config AUTO_CAST_FOR_DYNACONF=off|0|disabled|false

- HISTORY
- Makefile
- README.md
- docs/guides/configuration.md
- docs/guides/usage.md
- dynaconf/cli.py
- dynaconf/default_settings.py
- dynaconf/loaders/base.py
- dynaconf/loaders/ini_loader.py
- dynaconf/loaders/json_loader.py
- dynaconf/loaders/py_loader.py
- dynaconf/loaders/toml_loader.py
- dynaconf/loaders/yaml_loader.py
- dynaconf/utils/__init__.py
- example/common-encoding/.env
- example/common-encoding/.secrets.toml
- example/common-encoding/program.py
- example/common-encoding/settings.toml
- tests/test_cli.py
- tests/test_py_loader.py
- tests/test_utils.py
> IMPORTANT: Dynaconf by default reads settings files using `utf-8` encoding, if you have settings files written in other encoding please set `ENCODING_FOR_DYNACONF` environment variable see more in [configuration](https://dynaconf.readthedocs.io/en/latest/guides/configuration.html)
```
export ENCODING_FOR_DYNACONF="cp1252"
```
> Add ENCODING_FOR_DYNACONF to handle different file encoding Fix #81

- docs/guides/configuration.md
- dynaconf/base.py
- dynaconf/default_settings.py
- dynaconf/loaders/ini_loader.py
- dynaconf/loaders/json_loader.py
- dynaconf/loaders/py_loader.py
- dynaconf/loaders/toml_loader.py
- dynaconf/loaders/yaml_loader.py
- dynaconf/utils/__init__.py
- tests/test_base.py
- tests/test_utils.py
- Add the ability to merge nested structures instead of completely overwriting them
Please let me know if this looks like an acceptable solution, and what I should change to make it better.
> [RFR] Merge data structures

- .travis.yml
- tox.ini
These are a few test-only changes that I've been running locally for a little while now, and I thought I'd contribute them back upstream, if they're desired.
- Enables Python 3.7 testing on TravisCI via the usage of `dist: xenial`.
- Enables Python 3.7 in `tox.ini` environment list.
-  Update `py.test` command in `tox.ini` to allow passing positional arguments.
The basic, default functionality of running `tox` remains unchanged. You are now, however, able to pass positional arguments to `py.test` at invocation time. For example:
```bash
tox -- -x --pdb tests/test_basic.py
```
Which will pass all input after the `--` separator (which is used to signify the end of possible options to `tox`) down to the `py.test` command in the `{posargs}` location, as defined in `tox.ini`.
> Tox and TravisCI enhancements

- dynaconf/base.py
- example/full_example.py
- tests/test_base.py
To mirror the functionality added in #93, the ability to set nested structures has been added in this PR.
You can set a value with an arbitrary number of nested keys, separated by dots:
```python
settings.set('nested_1.nested_2.nested_3.nested_4', 'secret')
```
And accessing the keys/values with dotted-path lookup behaves as expected:
```python
print(settings.NESTED_1.NESTED_2.NESTED_3.to_dict())
```
If for some reason you didn't want to have a key parsed into nested structures delimited by dots and just wanted a key of "foo.bar", you can disable the parsing with:
```python
settings.set('nested_1.nested_2.nested_3.nested_4',
'secret',
dotted_lookup=False)
```
And accessing keys that don't exist will raise `KeyError`:
```python
settings.NESTED_1.NESTED_5
```
Tests have been added, and it …
> Allow dotted-path based setting of configuration key/value pairs.

- dynaconf/cli.py
- dynaconf/loaders/vault_loader.py
We want to be able to use a single Vault server for multiple environments. Currently, Dynaconf does not support multiple environments in Vault.
This PR adds the working environment into the path, so that the same Vault server can be used for multiple environments.
- Converted `os.path.join()` to `'/'.join()` as Vault only uses `/` and this would cause Dynaconf on Windows to provide an incorrect path to Vault.
> Add support for environments in Vault

- dynaconf/utils/__init__.py
- tests/test_base.py
* When using context managers, the loader is invoked each time.
This was slowing down in an exponential manner each time the it was run.
The eventual cause of this was down to an attribute being used as a list.
The object merge dutifully tried to expand this item out again and again
even in the case that the list was a single item, resulting in [item],
becoming [item, item]. The next time the merge was run, this process was
run again, but for each item in the list. In this particular instance
the list was identical, it meant that the list grew exponentially.
* This fix is a short optimization that checks to see if the old list
is identical to the new list. In which case, there is no merge to complete
so we simply return.
> Fix exponential slow down when loader is run multiple times

- dynaconf/base.py
- dynaconf/loaders/__init__.py
This fixes a bug where the default settings passed to the LazySettings constructor are merged with themselves when MERGE_ENABLED is true. This caused a conflict with django_dynaconf, which passes all of its settings as defaults. It did not produce immediate errors when loading django_dynaconf in INSTALLED_APPS because dynaconf was activated after application loading, but activating before application loading produces the error seen in #111.
The fix is to check for the existence of a setting before calling set() in default_loader.
> GH-111: Fix MERGE_ENABLED merging default settings with themselves

- Makefile
- docs/guides/configuration.md
- dynaconf/default_settings.py
- dynaconf/loaders/__init__.py
- example/jenkins_secrets_file/.env
- example/jenkins_secrets_file/app.py
- example/jenkins_secrets_file/jenkins_secrets.toml
- example/jenkins_secrets_file/settings.toml
- example/specific_settings_modules/.env
- example/specific_settings_modules/app.py
- example/specific_settings_modules/extra_settings.py
- example/specific_settings_modules/first_settings.toml
- example/specific_settings_modules/second_settings.toml
Now it is possible to export SECRETS_FOR_DYNACONF and have this
extra point loaded, like in a Jenkins CI you can specify on job.
```yaml
secret_file:
variable: SECRETS_FOR_DYNACONF
credentials:
type: specific_credentials
value: /path/to/secrets_file.toml{json,ini,yaml,py}
```
That variable can also be a list of paths.
Fix #117
> Fix #117 add support for extra secrets file (like for jenkins CI)

- Makefile
- azure-pipelines.yml
- docs/guides/environment_variables.md
- docs/guides/usage.md
- dynaconf/base.py
- dynaconf/loaders/base.py
- dynaconf/utils/__init__.py
- example/dynaconf_merge/.env
- example/dynaconf_merge/.secrets.toml
- example/dynaconf_merge/app.py
- example/dynaconf_merge/settings.toml
- tests/test_base.py
- tests/test_utils.py
If your settings has existing variables of types `list` ot `dict` and you want to `merge` instead of `override` then the `dynaconf_merge` and `dynaconf_merge_unique` stanzas can mark that variable as a candidate for merging.
Examples:
For a **dict** value:
Your main settings file (e.g `settings.toml`) has an existing `DATABASE` dict setting on `[default]` env.
Now you want to contribute to the same `DATABASE` key by addind new keys, so you can use `dynaconf_merge` at the end of your dict:
In specific `[envs]`
```toml
[default]
database = {host="server.com", user="default"}
[development]
database = {user="dev_user", dynaconf_merge=true}
[production]
database = {user="prod_user", dynaconf_merge=true}
```
In an environment variable:
```bash
export DYNACONF_DATABASE='{password=1234, …
```
> Add dynaconf_merge fucntionality for dict and list settings.

- dynaconf/validator.py
- requirements_dev.txt
- tests/test_validators.py
Hey @rochacbruno 👋 
So I've been using Dynaconf extensively for the past few days, and something I noticed with adding more Validators to my settings was a significantly increased delay in validation. With debug logging enabled it became obvious that for every Validator instance added to the settings, all loaders were re-run when doing `settings.validators.validate()`, i.e. eloading the entire environment once per Validator. 
That makes sense when a Validator instance has the `env=` param set to anything not equal to `settings.current_env` but not when the Validator is defined with `env=None` or equal to `settings.current_env`. In that case the `using_env` contextmanager would superfluously reload the current environment.
In this PR I separated the internal validation logic in …
> Skip reloading envs for validators that only apply to current_env

- Makefile
- docs/guides/configuration.md
- docs/guides/environment_variables.md
- dynaconf/loaders/env_loader.py
- example/global_env_prefix/.env
- example/global_env_prefix/app.py
- tests/test_env_loader.py
As discussed in #163, setting GLOBAL_ENV_FOR_DYNACONF='@none None', previously caused Dynaconf to only load env vars with a leading underscore, although it would be expected to load *all* vars. 
The necessary changes have been made to support explicit casting to NoneType through `'@none None'`, and forcing an "underscore-only prefix" by setting `GLOBAL_ENV_FOR_DYNACONF=""`. So:
* `GLOBAL_ENV_FOR_DYNACONF="EXAMPLE"` would load `EXAMPLE_VALUE=1` as settings.VALUE
* `GLOBAL_ENV_FOR_DYNACONF="none"` would load `NONE_VALUE=1` as settings.VALUE
* `GLOBAL_ENV_FOR_DYNACONF=""` would load `_VALUE=1` as settings.VALUE
* `GLOBAL_ENV_FOR_DYNACONF="@none None"` would load `VALUE=1`  as settings.VALUE, and all of the above verbatim, because no prefix would be enforced
> Fix #163 Allow disabling env prefix

- dynaconf/cli.py
To use click-web tool the module should be able to be explicitly called.
```
python -m dynaconf.cli
```
> Add explicit call to main() on cli.py

- dynaconf/loaders/base.py
- tests/test_envvar_prefix.py
When using `ENVVAR_PREFIX_FOR_DYNACONF=False` in LazySettings in combination with for example a TOML settings file, the base loader will raise an unexpected exception trying to `.lower`case the boolean. This MR appends `DYNACONF` as compatibility global_env instead when the `ENVVAR_PREFIX_FOR_DYNACONF` is `False`.
**Steps to reproduce the issue:**
1. Create TOML settings file `settings.toml` with the following contents:
```toml
[global]
var = 1
```
2. Try instantiating with `ENVVAR_PREFIX_FOR_DYNACONF=False`, and accessing an arbitrary value from the settings like so:
```python
settings = LazySettings(
ENVVAR_PREFIX_FOR_DYNACONF=False, 
SETTINGS_FILE_FOR_DYNACONF="settings.toml"
)
assert settings.VAR == 1
```
I added testcases to ensure this undefined behavior is properly prevented in the …
> Fix `False` not being an acceptable env

- .ci/test.sh
- Makefile
- requirements_dev.txt
- tox.ini
Now tests run in a separate tmpdir so xdist is not needed anymore
> removed pytest-xdist

- tests/test_compat.py
Previously whenever running the testsuite, Pytest would output the `DeprecationWarning`s that it was testing for in `test_compat.py`. I added the recwarn fixture to test if dynaconf outputs the right warnings, and at the same time hide the overly verbose output for the tests.
> Hide DeprecationWarning from Pytest when testing for them

- dynaconf/utils/__init__.py
In Python libraries it is advisable to _not_ use `logging.basicConfig` since the root logger configuration should be left to the application _using_ the library. To have a dynaconf-wide specific logger instance, a logger can be instantiated with a dedicated handler and it's own logging level.
This way a calling application can easily override these settings (directly or through `fileConfig`, `dictConfig`, etc.) while the previous behavior and response to `DEBUG_LEVEL_FOR_DYNACONF` of dynaconf stays intact.
> Replace logging.basicConfig with handler on logger

- dynaconf/utils/parse_conf.py
- tests/test_utils.py
I discovered what I would consider a bug, but @rochacbruno, you may correct me here, maybe this is expected behavior:
When an env var contains contents that are technically TOML-parsable but can not be retrieved from the (Dyna)Box, that raises a BoxKeyError, and causes the entire env_loader to drop out and parse none of the env vars at all.
To reproduce:
```bash
export DYNACONF_SOME_VAR="something=42"
python -c 'from dynaconf import settings; print(settings.SOME_VAR)'
```
Throws:
```
2019-05-07:15:13:29,634 ERROR    [env_loader.py:55 - load_from_env] "'DynaBox' object has no attribute 'KEY'"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/jan/Library/Caches/pypoetry/virtualenvs/protagonist-py3.7/lib/python3.7/site-packages/dynaconf/base.py", line 107, …
```
> Catch BoxKeyError when contents are TOML-parsable but not keyable

- dynaconf/base.py
- dynaconf/loaders/py_loader.py
- tests/test_nested_loading.py
- tests/test_py_loader.py
Dynaconf right now can load includes, the includes should be a list of paths like `['/path/to/file.yaml', '/path/to/glob/*.toml']`
**Problem**
It should also allow includes by `['python.module.paths'..]` instead of only `glob-able` paths.
**Describe the solution you'd like**
I want to be able to use:
```py
INCLUDES_FOR_DYNACONF=['python_module.submodule.settings', ...]
```
**Additional context**
This is request by  https://pulp.plan.io/issues/5290
The changes should go on lines:
https://github.com/rochacbruno/dynaconf/blob/master/dynaconf/base.py#L757-L799
And dynaconf already has ability to load Python modules on: https://github.com/rochacbruno/dynaconf/blob/master/dynaconf/loaders/py_loader.py
> Fix #207 allow python module path name for includes

- Makefile
- docs/guides/environment_variables.md
- docs/guides/usage.md
- docs/index.rst
- dynaconf/base.py
- dynaconf/default_settings.py
- dynaconf/loaders/env_loader.py
- dynaconf/loaders/py_loader.py
- dynaconf/utils/__init__.py
- dynaconf/utils/parse_conf.py
- example/dunder/.env
- example/dunder/app.py
- example/dunder/other_settings.py
- example/dunder/settings.py
- tests/conftest.py
- tests/test_base.py
- tests/test_env_loader.py
- tests/test_ini_loader.py
- tests/test_json_loader.py
- tests/test_nested_loading.py
- tests/test_py_loader.py
- tests/test_toml_loader.py
- tests/test_utils.py
- tests/test_yaml_loader.py
- tox.ini
Fix #197 
> **New in 2.0.5**
> 
> This is useful for `Django` settings.
Lets say you have a configuration like this:
`settings.py`
```py
DATABASES = {
'default': {
'NAME': 'db',
'ENGINE': 'module.foo.engine',
'ARGS': {'timeout': 30}
}
}
```
And  now you want to change the values of `ENGINE` to `other.module`, via environment variables you can use the format `${ENVVAR_PREFIX}_${VARIABLE}__${NESTED_ITEM}__${NESTED_ITEM}`
Each `__` (dunder, a.k.a *double underline*) denotes access to nested elements in a dictionary.
So 
```py
DATABASES['default']['ENGINE'] = 'other.module'
```
Can be expressed as environment variables as:
```bash
export DYNACONF_DATABASES__default__ENGINE=other.module
```
This will result in
```py
DATABASES = {
'default': {
'NAME': 'db',
'ENGINE': 'other.module',
'ARGS': …
```
> Fix #197 add support for DOTTED__ENV__VARS

- docs/guides/advanced_usage.md
- dynaconf/base.py
- dynaconf/cli.py
- dynaconf/contrib/django_dynaconf_v2.py
- dynaconf/loaders/__init__.py
- dynaconf/loaders/ini_loader.py
- dynaconf/utils/__init__.py
- example/django_example_compat/foo/settings.py
- tests/test_base.py
Ref #218 
`settings._store` is now a `DynaBox` and that allows first level keys to be lower case.
Ref #211 
`settings` now has a `from_env` method to allow switching branches without side effects.
You can switch between existing environments using:
- `from_env`: (**recommended**) Will create a new settings instance pointing to defined env.
- `setenv`: Will set the existing instance to defined env.
- `using_env`: Context manager that will have defined env only inside its scope.
> **New in 2.0.5**
Return a new isolated settings object pointing to specified env.
Example of settings.toml::
```ini
[development]
message = 'This is in dev'
foo = 1
[other]
message = 'this is in other env'
bar = 2
```
Program::
```py
>>> from dynaconf import settings
>>> print(settings.MESSAGE)
'This is in dev' …
```
> Adds `from_env` method and change `_store` to be a `DynaBox`

- dynaconf/base.py
I was hitting an error like below:
```---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-c4a32dfb6df1> in <module>
----> 1 cfme_data.management_systems
/var/ci/workspace/kkulkarn-9315/integration_tests/cfme/utils/config_data.py in __getattr__(self, key)
14 
15     def __getattr__(self, key):
---> 16         self.config = self.settings[key.upper()]
17         return self.config
18 
/var/ci/cfme_venv3/lib64/python3.7/site-packages/dynaconf/utils/functional.py in inner(self, *args)
8     def inner(self, *args):
9         if self._wrapped is empty:
---> 10             self._setup()
11         return func(self._wrapped, *args)
12 …
```
> Fixing self._root_path to fall back to os.getcwd()

- dynaconf/loaders/base.py
- tests/test_yaml_loader.py
Dynaconf crashes when used with empty settings.
Create a settings.yaml file with the following content:
`default: ~`
Run the following:
```
from dynaconf import settings
settings.reload()
```
It crashes with an `AttributeError: 'NoneType' object has no attribute 'items'`
I managed to trace it to a bug in the BaseLoader:
```
data = {}
try:
data = source_data[env]
except KeyError:
[...]
data = {upperfy(k): v for k, v in data.items()}
```
This works fine when env doesn't exist, or when environment contains values, but "source_data[env]" is `None` when passed an empty settings file. Adding `data = source_data[env] or {}` fixes it and is consistent with the definition of data that was the line before.
> fix crash on empty settings

- docs/guides/advanced_usage.md
- docs/guides/configuration.md
- docs/guides/usage.md
- dynaconf/base.py
- dynaconf/default_settings.py
- tests/test_base.py
Ref https://github.com/pulp/pulpcore/pull/330
Useful for plugin based apps.
```py
from dynaconf import LazySettings
settings = LazySettings(
PRELOAD_FOR_DYNACONF=["/path/*", "other/settings.toml"],                # <-- Loaded first
SETTINGS_FILE_FOR_DYNACONF="/etc/foo/settings.py",                      # <-- Loaded second (the main file)
INCLUDES_FOR_DYNACONF=["other.module.settings", "other/settings.yaml"]  # <-- Loaded at the end
)
```
> Add support for PRELOAD_ setting.

- dynaconf/base.py
- example/issues/251_dotted_unexistent/app.py
- example/issues/251_dotted_unexistent/settings.py
Fix #251 
replaced with recursive passing of parent data.
NOTE to SELF: Never! use a mutable memoized data
Always use `==` to compare when you dont know the types
> Fix #251 recursive call was using mutable memoized data

- tests/test_validators.py
Validator was missing coverage for comparison by identity.
ex:
```
validator = Validator(...)
validator2 = validator
assert validator == validator2
```
> Fix coverage for validators

- requirements_dev.txt
- setup.py
The release of python-box https://github.com/cdgriffith/Box/pull/116
is a breaking change.
So pinning this until this project addapts.
Also pinning other direct deps.
Reported on: https://twitter.com/maszanchi/status/1210123455594545154
> Pin python-box version because of a breaking release

- .pre-commit-config.yaml
Running "make all" in a python3.6 environment breaks on pre-commit, because of a call to "python3.7". Fixed by calling "python3".
> Fix pre-commit to run python3 rather than python3.7

- Makefile
- docs/guides/environment_variables.md
- docs/guides/usage.md
- dynaconf/base.py
- dynaconf/utils/parse_conf.py
- example/format/.env
- example/format/app.py
- example/format/settings.toml
- tests/test_utils.py
Dynaconf has 2 tokens to enable string substitutions `@format` and `@jinja`.
Dynaconf allows template substitutions for strings values, by using the `@format` token prefix and including placeholders accepted by Python's `str.format` method Dynaconf will call
it lazily upon access time.
The call will be like:
```py
"<YOURVALUE>".format(env=os.environ, this=dynaconf.settings)
```
So in your string you can refer to environment variables via `env` object, and also to variables defined int the settings object itself via `this` reference. It is lazily evaluated on access it will use the final value for a settings regardless the order of load.
Example:
```bash
export PROGRAM_NAME=calculator
```
settings.toml
```toml
[default]
DB_NAME = "mydb.db"
[development]
DB_PATH = "@format …
```
> Fix #145 allow string formatting using envvars

- Makefile
- example/overriding/.env
- example/overriding/app.py
- example/overriding/settings.py
- example/overriding/user_settings.py
[13:04:45] <@bmbouter> rochacbruno: can you help me w/ a dynaconf example I'm writing for the docs
[13:04:59] <rochacbruno> bmbouter: sure!
[13:05:04] <rochacbruno> I hope so
[13:05:12] <bmbouter> I want an example of overridding the DEFAULT_AUTHENTICATION_CLASSES key in this dict https://github.com/pulp/pulpcore/blob/master/pulpcore/app/settings.py#L125
[13:05:16] <bmbouter> and leave the other keys alone
[13:05:36] <bmbouter> and my goal is to keep L#126 and L#128 but effectively remove L#127
[13:07:05] <rochacbruno> bmbouter: let me see, one moment
[13:08:44] <bmbouter> thank you!
Lets say you have:
```py
DATA = {
'FOO': [1, 2, 3]
}
```
and your goal is to override `settings.DATA.FOO` to be equal to `[1, 3]` (remove the item `2`
On `user_settings.py`
```py
DATA__FOO = "@reset [1, 3]" …
```
> adoverriding strategy

- Makefile
- docs/guides/testing.md
- dynaconf/contrib/django_dynaconf_v2.py
- dynaconf/contrib/flask_dynaconf.py
- example/pytest_example/app/.env
- example/pytest_example/app/app.py
- example/pytest_example/app/settings.toml
- example/pytest_example/app/tests/conftest.py
- example/pytest_example/app/tests/test_dynaconf.py
- example/pytest_example/flask/.env
- example/pytest_example/flask/settings.toml
- example/pytest_example/flask/src.py
- example/pytest_example/flask/tests/conftest.py
- example/pytest_example/flask/tests/test_flask_dynaconf.py
Fix #203
For pytest it is common to create fixtures to provide pre-configured settings object or to configure the settings before
all the tests are collected.
Examples available on [https://github.com/rochacbruno/dynaconf/tree/issue_203/example/pytest_example](https://github.com/rochacbruno/dynaconf/tree/issue_203/example/pytest_example)
With `pytest` fixtures it is recommended to use the `FORCE_ENV_FOR_DYNACONF` isntead of just `ENV_FOR_DYNACONF` because it has precedence.
`settings.toml` with the `[testing]` environment.
```toml
[default]
VALUE = "On Default"
[testing]
VALUE = "On Testing"
```
`app.py` that reads that value from current environment.
```py
from dynaconf import settings
def return_a_value():
return settings.VALUE
```
`tests/conftest.py` with a fixture to force `settings` …
> Fix #203 document the usage with pytest (with examples)

- docs/guides/flask.md
Just a minor typo in the flask extension docs
> Fix minor typo in Flask extension docs

- dynaconf/base.py
- dynaconf/contrib/django_dynaconf/dynaconf_django_conf.py
- dynaconf/contrib/flask_dynaconf.py
- example/compat.py
- example/validators/with_python/conf.py
- tests/test_base.py
Now when creating a `LazySettings` instance one can use aliases
So instead of `LazySettings("ENV_FOR_DYNACONF='FOO'")` it can be:
`LazySettings(ENV="FOO")`
> Add support for aliased configs

- Makefile
- docs/guides/advanced_usage.md
- docs/guides/configuration.md
- dynaconf/base.py
- dynaconf/loaders/base.py
- example/lower_read/app.py
- example/lower_read/settings.yaml
- tests/test_base.py
Fix #272 allow access of lowercase keys
- `settings.lowercase_key` is allowed
- `settings.dynaconf` is a proxy to internal methods
- `settings.__reserved_attributes` validates key names
- `LazySettings __init__ parameters can receive lower case configs`
> Fix #272 allow lowercase keys

- dynaconf/validator.py
According to the documentation (https://www.dynaconf.com/validation/) Validator should treat all fields as optional unless `must_exist` option is set, but it doesn't work as expected. 
In the example below we have optional setting `optional_settings` in config but validator fails with error if this setting is not present:
```
Traceback (most recent call last):
File "test.py", line 15, in <module>
settings.validators.validate()
File "/Users/piotr/Documents/Repos/dynaconf/dynaconf/validator.py", line 288, in validate
validator.validate(self.settings)
File "/Users/piotr/Documents/Repos/dynaconf/dynaconf/validator.py", line 163, in validate
self._validate_items(settings, settings.current_env)
File "/Users/piotr/Documents/Repos/dynaconf/dynaconf/validator.py", line 208, in _validate_items …
```
> Fix validation of optional fields

- docs/validation.md
- dynaconf/base.py
- dynaconf/validator.py
- example/issues/377_default_validators/app.py
- example/issues/377_default_validators/settings.toml
- tests/test_validators.py
Fix #377 
Validators can be used to provide default or computed values.
```py
Validator("FOO", default="A default value for foo")
```
Then if not able to load the values from files or environment this default value will be set for that key.
Sometimes you need some values to be computed by calling functions, just passa a callable to the `default` argument.
```py
Validator("FOO", default=my_dunction)
```
then
```py
def my_function(settings, validator):
return "this is computed during validation time"
```
If you want to be lazy evaluated
```py
from dynaconf.utils.parse_conf import empty, Lazy
Validator("FOO", default=Lazy(empty, formatter=my_function))
```
> Fix #377 allow default and computed values

- tests/test_redis.py
This is used for https://build.opensuse.org/request/show/825159 , so that the redis integration can be tests in an isolated environment without access to the internet.
> Allow testing against local redis server

- dynaconf/utils/files.py
Hello,
I am a fairly new user of dynaconf (it's an awesome package btw 💖 🙇  ) and I ran into an issue where I wanted to display the search tree to the user so that they understand where they can place their config files so that they are discovered. I imported `SEARCHTREE` before settings were configured and then it won't update after they are. This commit fixes this minor issue...
<br>
Currently: if `dynaconf.utils.files.SEARCHTREE` is imported before settings are configured, it stays `None`.
This commit allows usercode to import `SEARCHTREE` before dynaconf is configured, and have it be updated as soon as it is.
```python
from dynaconf.utils.files import SEARCHTREE
settings = DynaConf(...)
settings.configure()
```
**NOTE:** this is a potentially breaking …
> Allow importing SEARCHTREE before settings are configured

- dynaconf/validator.py
- tests/test_validators.py
`Validator(must_exist=False)` incorrectly checks first name only.
Given `settings.yaml`:
bar: some_value
and app.py:
```python
from dynaconf import Validator
settings = Dynaconf(
settings_files=['settings.yaml', '.secrets.yaml'],
validators=[Validator("foo", "bar", must_exist=False)],
)
settings.validators.validate()
```
Running `app.py` does not result in `ValidationError` being rised - even though "bar" is defined.
tests:
```
$ pytest -v -k test_validation_error tests/
===================================================================================== test session starts =====================================================================================
platform linux -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- …
```
> Test all names in Validator("foo", "bar", must_exist=False)

- docs/index.md
[The Initialize Dynaconf on your project](https://www.dynaconf.com/#initialize-dynaconf-on-your-project) use `dynaconf init -f toml` to generate.toml files, but yaml files are used in the Initialize code `config.py`, which is an obvious error and confuses the reader.
> docs: Fixed filename error in the case of the index page

- 3.x-release-notes.md
- README.md
- docs/advanced.md
- docs/cli.md
- docs/configuration.md
- docs/django.md
- docs/dynamic.md
- docs/envvars.md
- docs/flask.md
- docs/index.md
- docs/merging.md
- docs/release_notes.md
- docs/secrets.md
- docs/settings_files.md
- docs/validation.md
I ran through all `.md` files with a spellchecker after finding a few small typos.
I skipped CHANGELOG.md, however.
> Correct typos in documentation and README

- docs/validation.md
There was a typo in the function name. This fixes it.
> Fix typo in Validation docs

- dynaconf/utils/boxing.py
Dynaconf is trying to detect a lazy formattable value by the presence of `formatter` attribute but in Django `LOGGING` has a `.formatter` and it is going to fail.
> Fix django logging conflict

- Makefile
- dynaconf/base.py
- dynaconf/default_settings.py
- example/issues/253_set/app.py
- example/issues/392_evaluate_nested_structures/app.py
Fix #253
Fix #395
Allows `settings.FOO = 1` and fixes some fresh_vars issues
> Fix set attribute directly and fresh vars

- dynaconf/validator.py
- tests/test_validators.py
Fix bug reported as #407 by introduction of proper equality test in `CombinedValidator`.
I considered adding new `combined_attributes` property to `Validator`, something that would return tuple of all attributes mentioned in `__eq__` method. Then `CombinedValidator` would override this property and return tuple of two validators `combined_attributes`.
However, the other method didn't allow to provide custom properties values by instantiating `CombinedValidator` directly. In current approach, following does work:
```python
from dynaconf.validator import Validator, AndValidator
a1 = AndValidator(Validator("FOO"), Validator("BAR"), when=Validator("BASE", must_exist=True))
a2 = AndValidator(Validator("FOO"), Validator("BAR"), when=Validator("FOUNDATION", must_exist=True))
assert a1 != a2
``` …
> Fix #407 - add proper equality test for CombinedValidator

- Makefile
- dynaconf/validator.py
- example/issues/404_dup_validator_message/app.py
> Fix #404 no more dup message on combined validators

- Makefile
- dynaconf/utils/__init__.py
- example/issues/443_object_merge/README.md
- example/issues/443_object_merge/app.py
This solution is a temporary solution as it solves current
problem, but there is still the case for `None` values.
The best solution for this case would be wrapping all the values
on assignment and give it a full path signature to compare.
Fix #443
> Fix #443 object merge with same value on same level keys

- docs/flask.md
- dynaconf/contrib/flask_dynaconf.py
- example/dummy_flask_extension/README.md
- example/dummy_flask_extension/__init__.py
- tests/test_flask.py
An idiomatic pattern for many Flask extensions is to instantiate the extension at "import time", and call `[instance].init_app()` dynamically at run time.  E.g.:
```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
db = SQLAlchemy()
def application_factory(*args, **kwargs):
app = flask.Flask(*args, **kwargs)
db.init_app(app)
return app
```
This pattern is incompatible with the current implementation of `FlaskDynaconf.load_extensions`.  The current implementation allows for an import path specifying a module, and a single attribute of that module specifying the initialization callable.  E.g. `“flask_admin:Admin”` or `“extension.module:init_app”`.  However, there does not appear to be a way to specify calling a method of a "global" instance as above.
Fortunately, Python's …
> Specify flask extension initializers by entry point object reference

- dynaconf/loaders/__init__.py
I used _map_ and _str.upper_ to transform all string to uppercase and make _enabled_core_loaders_ case sensitive.
> Changed enabled_core_loaders elements to be upper case to fix #455

- docs/envvars.md
- dynaconf/default_settings.py
- dynaconf/loaders/env_loader.py
- example/ignore_unknown_envvars/.env
- example/ignore_unknown_envvars/app.py
- example/ignore_unknown_envvars/settings.toml
- tests/test_env_loader.py
Fixes #470 
Added new global option `ignore_unknown_envvars` / `IGNORE_UNKNOWN_ENVVARS_FOR_DYNACONF`.
Included is example app and some docs changes describing the usage.
> Fix: Environment variables filtering #470

- Makefile
- docs/django.md
- docs/index.md
- dynaconf/utils/__init__.py
- example/issues/519_underscore_in_name/app.py
- example/issues/519_underscore_in_name/settings.yml
Fix #519
Fix #516
Now `export DYNACONF_FOO__bar__zaz` is the same as
`DYNACONF_FOO__BAR__ZAZ`
> first level prefix still needs to be uppercase!
Added a warning about django to the docs.
> Case insensitive envvar traversal

- Makefile
- dynaconf/base.py
- example/issues/478_mispell_environments/app.py
- example/issues/478_mispell_environments/settings.toml
This is a commom mistake to pass `environment` so it is alias.
Fix #478
> Fix #478 Make alias for environment -> environments

- Makefile
- dynaconf/base.py
- example/issues/449_django_lazy_path/foo/settings.py
In order to keep the same method api, default values should be parsed
and converted to Boxed objects.
https://github.com/rochacbruno/dynaconf/issues/462
> HOTFIX for 462 related issue, `default` on .get should be parsed as Box objects

- .gitignore
- .pre-commit-config.yaml
- docs/dynamic.md
- dynaconf/loaders/base.py
- example/issues/379_dict_like_iteration/app.py
- example/issues/519_underscore_in_name/app.py
- mkdocs.yml
- tests/test_envvar_prefix.py
towncrier will be implemented soon
> removed release_notes from the docs.

- docs/validation.md
- dynaconf/base.py
- dynaconf/validator.py
- example/validators/with_python/conf.py
- tests/test_validators.py
This change introduces the ability to control which sections of a
settings object are subject to validation.
This is controlled primarily by two mechanisms.
1: When creating a settings object, new arguments `validate_only`
and `validate_exclude` have been added which receive a list of settings
paths.
2: When manually calling validate, new arguments `only` and `exclude`
have been added.
All of these allow for either a string or list of strings representing
settings paths. For example:
`settings.validators.validate(only=["settings.something",
"settings.another"])`
settings = Dynaconf(..., validate_exclude="settings.bad")
Fixes #508
> Add the ability for selective validation

- dynaconf/contrib/flask_dynaconf.py
- tests/test_flask.py
Include **all** values when iterating over `dynaconf.contrib.flask_dynaconf.DynaconfConfig`
The standard mapping iterator methods (i.e., `.keys()`, `.values()`, `.items()`, `.__iter__()`) of the `dynaconf.contrib.flask_dynaconf.DynaconfConfig` object use the default `dict` implementations and do not include values from the encapsulated `dynaconf.LazySettings` object.  Any values added via `FlaskDynaconf.__setitem__` are only added to the encapsulated `LazySettings` and are not included in any iteration over the `DynaconfConfig` object.  E.g.:
```
from flask import Flask
from dynaconf.contrib import FlaskDynaconf
app = Flask(__name__)
app.config['BEFORE_DYNACONF'] = 'before dynaconf'
app.config['MUTABLE'] = 'original'
FlaskDynaconf(app)
app.config['AFTER_DYNACONF'] = 'after dynaconf' …
```
> fix dict iterator methods for flask DynaconfConfig

- example/fastapi_with_ini/app.py
- example/fastapi_with_ini/config.toml
Added an example showing how FastAPI can be used to view settings.
> Added an example using FastAPI

- docs/configuration.md
- dynaconf/base.py
- dynaconf/loaders/base.py
- dynaconf/loaders/ini_loader.py
- dynaconf/loaders/json_loader.py
- dynaconf/loaders/toml_loader.py
- dynaconf/loaders/yaml_loader.py
- dynaconf/strategies/filtering.py
- example/toml_example/app.py
- example/toml_example/settings.toml
- example/yaml_example/settings_file/app.py
- example/yaml_example/settings_file/settings.yaml
- example/yaml_example/yaml_as_extra_config/app.py
- example/yaml_example/yaml_as_extra_config/settings.py
- tests/test_base.py
- tests/test_ini_loader.py
- tests/test_json_loader.py
- tests/test_toml_loader.py
- tests/test_yaml_loader.py
Related to: #621
This adds a settings_file_prefix option for toml, json, ini and yaml files which works similarly to envvar_prefix, however it defaults to None and does not filter out any keys if it is not set.
If envs are in use it will do the filtering within each env's variables, an example is shown below
```
[default]
PREFIX_EXTRA = "this will supercede if others are set without prefix"
[development]
PREFIX_HOST = "https://example.com/development"
PREFIX_PORT = "8080"
COMMENT = "this will not show when prefix is used"
EXTRA = "will not show"
[production]
PREFIX_HOST = "https://example.com/production"
PORT = "443"
EXTRA = "will not show"
```
When these are loaded up using the `settings_file_prefix="PREFIX"` option you'll get the following:
```
>>> settings.HOST …
```
> feat: add filter strategy with PrefixFilter

- docs/cli.md
- dynaconf/cli.py
- tests/test_cli.py
Updated the CLI Click help strings, added in a warning print if `--env/-e` is passed to `init` to mention that it is a deprecated option an has no effect, also added a condition to raise an exception if `dynaconf -i ... init` is called as using instance with the init subcommand doesn't work and the standard exception may not be too clear.
Also updated `docs/cli.md` to be in sync with new help output from the subcommands, and to reflect the deprecation of `dynaconf init --env ...`.
Closes https://github.com/rochacbruno/dynaconf/issues/589
> Add a warning if `--env` is passed to `init`

- dynaconf/validator.py
- tests/test_validators.py
Added description to Validator
```py
Validator("foo", description="foo description")
```
Given a ValidatorList one can do.
```py
>>> settings.validators.descriptions(flat=True)
{"foo": "foo description"}
```
Not sure what to do with this yet but the support is added.
Probably the next step is to add a `CLI` to fetch those descriptions and generate/export settings files with descriptions as hints.
Fix: #115
> description and type annotation for validator

- dynaconf/base.py
- tests/test_base.py
Add boolean variable inside `_merge_before_set()` method to check if the environment was set as default to change the unique bool to True to solve bug when merging two lists described in issue #653.
> Add unique label when merging lists to fix issue #653

- docs/merging.md
- dynaconf/base.py
- dynaconf/loaders/base.py
- dynaconf/utils/__init__.py
- dynaconf/utils/parse_conf.py
- example/compat.py
- tests/test_base.py
- tests/test_utils.py
- tests/test_yaml_loader.py
also stopped using `/tmp` on tests (using tempfile instead)
> Found this bug that was duplicating the generated envlist

- .github/workflows/update_contributors.yml
- dynaconf/contrib/flask_dynaconf.py
- tests/test_flask.py
Currently, it only checks the underlying dict but not the Dynaconf instance, resulting in the wrong return value if the key exists in the Dynaconf instance.
> Fix FlaskConfig.setdefault

- .github/workflows/update_contributors.yml
- Makefile
- docs/settings_files.md
- example/-m_case/module/__main__.py
- example/-m_case/module/config/settings.toml
- example/format/.env
- example/format/app.py
- example/format/settings.toml
> Document the usage with python -m

- .github/workflows/update_contributors.yml
- dynaconf/utils/parse_conf.py
- tests/test_utils.py
Related to issue: #642 
* Implemented the following casting cases that are compatible with `@jinja` and `@format`:
- `@str`: casting parsed results to string
- `@int`: casting parsed results to integer
- `@float`: casting parsed results to float
- `@bool`: casting parsed results to boolean
- `@json`: casting parsed results to dictionary
* Updated `Lazy` class under `utils/parse_conf.py`
- Added the `casting` argument
- Adding the method `set_casting(self, casting)`
* Added the unit test for the above casting.
```yaml
NUM_GPUS: 4
FOO: "@int @jinja {{ this.NUM_GPUS }}"
FOO: "@jinja {{ this.NUM_GPUS }}"
```
```yaml
MODEL_1:
MODEL_PATH: "src.main.models.CNNModel"
GPU_COUNT: 4
OPTIMIZER_KWARGS:
learning_rate: 0.002
MODEL_2:
MODEL_PATH: "src.main.models.VGGModel"
GPU_COUNT: 2
OPTIMIZER_KWARGS: …
```
> Feature: add @jinja and @format casting

- docs/flask.md
- dynaconf/contrib/django_dynaconf_v2.py
- dynaconf/contrib/flask_dynaconf.py
This transforms all kwargs in Flask/Django to upper case, making it possible for the user to pass `envvar_prefix` (and other kwargs) the same way as in the default `Dynaconf` class. The current behavior accepts only uppercase kwargs, making `envvar_prefix` not work as expected.
This also improves documentation for future use -> Line54 of the `flask.md` does need to be updated depending on which version when/if this get's released.
> Makes Django/Flask kwargs case insensitive

- dynaconf/base.py
- dynaconf/default_settings.py
- dynaconf/loaders/vault_loader.py
Problem Statement:
--------------------
This PR fixes #723 !
The issue is observed when the secrets are created in Vault store without using DynaConf way of creating it that is CLI way of `dynaconf write` or using dynaconf APIs.
The secrets were directly created to `MOUNT_POINT/PATH` using Hashicorp vault CLI / API and hence the dynaconf environments were not created there. 
So while reading these non-dynaconf/non-environemnts based secrets from Vault using DynaConf, we were hitting to the wrong path, that is:
- if we set environments of dynaconf to True (`Dynaconf(environments=True)`) then we hit the developement enviroments path that is : `mount_point/path/developement`.
- if we set environments of dynaconf to False (`Dynaconf()`) then we hit the main environments path that is : …
> Load vault secrets from environment less stores or which are not written by dynaconf

- dynaconf/base.py
Problem Statement:
-----------------------
Currently, when the value for a setting is blank in YAML, the dynaconf settings object is returning the None value instead of what's set as a default parameter.
The Validator example - `Validator('azurerm.client_secret', default='myAzurePass'),` is returning None when client_secret is set blank in azure.yaml
Expected:
-----------
When the Settings is set to blank in the YAML file then it must use the default value.
The Validator example - `Validator('azurerm.client_secret', default='myAzurePass'),` should return 'myAzurePass' when client_secret is set blank in azure.yaml
Solution:
----------
The `setdefault` method in the dynaconf settings class is updated to accept the value as blank to return the value from default parameter.
> Use default value when settings is blank

- Makefile
- docs/validation.md
- dynaconf/base.py
- dynaconf/validator.py
- example/issues/734_validate_only_current_env/app.py
- example/issues/734_validate_only_current_env/settings.toml
- tests/test_validators.py
As discussed in [issue 734](https://github.com/rochacbruno/dynaconf/issues/734), added a new keyword for `validator.validate` and `Settings` class to only run validators on current env instead of all defined envs.
Hope everything is fine, feel free to mention any issue and I'll try to fix them.
> Added validate_only_current_env to validator (issue #734)

- README.md
Fixing a typo on the readme file (setttings -> settings)
> Fixing a typo on the readme file

- .github/workflows/main.yml
Looks like the codecov action v1 is deprecated (see https://github.com/codecov/codecov-action#%EF%B8%8F--deprecation-of-v1). Bumping to the v3.
> Bump codecov action version

- Makefile
- dynaconf/cli.py
- example/issues/705_flask_dynaconf_init/Makefile
- example/issues/705_flask_dynaconf_init/app.py
Fixed the problem with the init cli command when the FLASK_APP variable is set. Now cli warps the app and app.config objects and pass settings object to the init call. 
Added also simple example how to reproduce this problem.
> Fix cli init command for flask (#705)

- Makefile
- docs/envvars.md
Solving https://github.com/dynaconf/dynaconf/issues/790
Adding documentation about adding custom casting tokens and add running of example to makefile.
> Adding documentation and example to makefile.

- dynaconf/utils/__init__.py
- dynaconf/utils/boxing.py
- tests/test_yaml_loader.py
existing data is
```yaml
level1:
KeY4:
```
envvars is
```console
$ export DYNACONF_LEVEL1__KEY4=foo
```
Then
```
settings._store
```
Fix #737
> New data key casing must adapt to existing key casing

- dynaconf/cli.py
> Fix get command with Django

- dynaconf/utils/__init__.py
- tests_functional/issues/726_unique_nested_list/app.py
- tests_functional/issues/726_unique_nested_list/configuration.yaml
- tests_functional/issues/726_unique_nested_list/defaults.yaml
> Allow merge_unique on lists when merge_enabled=True

- dynaconf/base.py
- tests_functional/issues/728_pytest/Makefile
- tests_functional/issues/728_pytest/config.py
- tests_functional/issues/728_pytest/settings.toml
- tests_functional/issues/728_pytest/tests.py
Rebind current env when forced for Pytest Fix #728
> Rebind current env when forced for Pytest Fix #728

- docs/envvars.md
Old:
`export PREFIX_PATH='@format {env{"HOME"}/.config/{this.DB_NAME}'`
Error:
ValueError: unexpected '{' in field name
Fixed:
`export PREFIX_PATH='@format {env[HOME]}/.config/{this.DB_NAME}'`
> fix: envvars.md get `HOME` environment variable

- .pre-commit-config.yaml
- dynaconf/cli.py
- dynaconf/loaders/env_loader.py
- dynaconf/utils/files.py
- tests_functional/missing_pwd/test.sh
- tests_functional/runtests.py
- tests_functional/skipfile.toml
Fixes https://github.com/dynaconf/dynaconf/issues/853
Reproducer:
```bash
#!/bin/bash
rm -rf /tmp/foobar
mkdir -p /tmp/foobar
cd /tmp/foobar
rm -rf /tmp/foobar
echo "PWD:$(pwd)"
dynaconf list
```
> Handle all failures when pwd does not exist.

- dynaconf/default_settings.py
This should allow us to use namespaces for vault without having to specify `VAULT_FOR_DYNACONF` with the entire config.
> Add support for VAULT_NAMESPACE_FOR_DYNACONF

- docs/advanced.md
Fix syntax error, missing comma
```
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```
> Fix code snippet in docs

- docs/envvars.md
I noticed a few typos in reading the docs for this page. Thanks for this awesome package!
> Fix typos in envvars docs

- dynaconf/utils/files.py
- tests_functional/issues/876_deleted_cwd/app.py
- tests_functional/issues/876_deleted_cwd/test.sh
- tests_functional/skipfile.toml
When the settings_file is provided as an absolute path dynaconf will not error even if cwd doesn't exist.
The fix was to check for absolute path first.
For relative paths the cwd is still required.
> fix #876 - avoid failure on deleted cwd

- .github/workflows/main.yml
According to the [docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore), this would trigger the CI if at least one file that is not specified in the `path-ignore` is modified.
Also, the Netlify workflow should trigger just when some changes are made to docs, right?
Assuming mkdocs currently doesn't rely on code to generate text, like using docstrings from code or something.
I did not include this change because the Netlify action file is not present in the `.github/` folder. Maybe it is editable from the GH web interface.
> CI - Prevent running when just doc changes are made

- docs/django.md
- docs/envvars.md
- docs/faq.md
- requirements_dev.txt
- The modification in the `requirements-dev.txt` triggered the CI. The mkdocs plugin I added was only present in the `requirements.txt` (which is intended for netlify only), so `make` would not install it automatically.
- The main modification (**django page** and **faq page**) refers to discussions #865 and #858 
- A small unrelated contribution (**envvar page**) to #860 
- General and small readability/styling tweaks and typo fixes
> Docs - Django functions in settings file and misc

- docs/configuration.md
- docs/faq.md
- docs/settings_files.md
- dynaconf/base.py
- dynaconf/utils/__init__.py
- Add faq about #712 and #792
- Fix wrong info as reported in #898
- Change `dynaconf_include` to accept `str` (like `includes_for_dynaconf`) as proposed [here](https://github.com/dynaconf/dynaconf/issues/898#issuecomment-1478428723).
> Docs - Add faq and fix `includes` info

- dynaconf/base.py
- tests_functional/issues/905_item_duplication_in_list/.env
- tests_functional/issues/905_item_duplication_in_list/README.md
- tests_functional/issues/905_item_duplication_in_list/app.py
- tests_functional/issues/905_item_duplication_in_list/settings.toml
This fixes #905
---
Just for the records, I'll try to explain what I've understood about the problem, sorry if it is too confusing.
One of the key-point of the problem was that the process of setting the default for the Validator uses `tomlfy=True` and this causes some side-effect on the `default` field siblings.
In the last step of recording this value there is a `merge_before_set(new, old)` function. I would expect that the new data to be merged in the existing data would be only the `default` value provided in Validation, but all of it's siblings are used too (including list).
Before this merge, `parse_conf_data(data, tomlfy=True, ...)` is called with 'default' value and all of it's existing siblings, and this makes `new` and `old` data to have different version of `test_list`, one …
> Fix - Array entries duplicated when using Validator with default for computed value

- docs/configuration.md
- dynaconf/base.py
- dynaconf/default_settings.py
- tests/test_base.py
I've changed the proposed name in the original issue from `fallback_to_environ` to `sysenv_fallback` to stress that those are system environment variables, but it is totally fine to switch it back or to another name.
Also, I had some doubts on dealing with mixed casing, because windows seems to uppercase all environment variables and linux don't. To be safe, I chose to implement an uppercased-lookup of system variables, even though linux would support matching mixed-case.
> Feature - Allow system environment fallback in `get()` #742

- docs/advanced.md
- docs/configuration.md
- docs/settings_files.md
- dynaconf/base.py
Clarification about:
- `load_file` relative path resolution, which relies on `root_path`.
- `root_path`implicit setting, when not explicit defined via `ROOT_PATH_FOR_DYNACONF`.
Also:
- Small docstring appends on `load_file`
ps:
I'll leave the idea of [dot expansion](https://github.com/dynaconf/dynaconf/issues/909#issuecomment-1511918263) to v4 ([proposal](https://github.com/dynaconf/dynaconf/issues/923))
> Docs - `load_file` relative path resolution and `root_path` fallbacks #909

- docs/index.md
- dynaconf/utils/parse_conf.py
I'm not sure why this was supported before `v3.1.12` (see #919), because I didn't find explicit support for integer keys.
Anyway, the `ruamel.yaml` parser doesn't cast key integers to string (as toml parser does, for example), and some part of the system assumes all keys are strings, which I guess is a sane choice.
I've considered two approaches, assuming all int keys should be strings internally:
- Casting keys to integers in the loader level. This would require hacking the yaml parser (I guess this is not customizable) or writing a pos-parser to cast keys to string (this would cause some overhead, as all data would need to be traversed again).
- Cast keys when parsing them internally (`Settings.set`, `Settings.parse_conf`, etc). This wouldn't add overhead because the data need to pass …
> Fix AttributeError with integer keys (yaml) #919

- dynaconf/contrib/flask_dynaconf.py
This PR removes the dependency on pkg_resources and relies on stdlib importlib.metadata instead. This fixes the problem described in issue #851.
> Replace pkg_resources with importlib.metadata

- .github/workflows/main.yml
- dynaconf/base.py
- dynaconf/cli.py
- dynaconf/loaders/py_loader.py
- dynaconf/utils/__init__.py
- dynaconf/utils/boxing.py
- dynaconf/utils/inspect.py
- dynaconf/utils/parse_conf.py
- dynaconf/vendor/box/box.py
- tests/docker-compose.yml
- tests/test_inspect.py
- tests_functional/issues/575_603_666_690__envvar_with_template_substitution/Makefile
- tests_functional/issues/575_603_666_690__envvar_with_template_substitution/app_test.py
- tests_functional/issues/879_cli_validate_isinstance/pyrightconfig.json
- tests_functional/test_vault.sh
- tests_functional/test_vault_userpass.sh
This fixes the misbehavior of template substitution when the variable to be substituted gets updated by another source, as described in #575 #603 #666 and #690
**Main changes:**
- avoid replacement of `Lazy` objects by it's value inside `parse_conf_data`
- add `_safe_get` and `_safe_items` methods to `DynaBox`.
- small unrelated refactors
There were some points where earlier evaluation was called internally. Although those calls were unnecessary, they shouldn't have cause this bug by itself because evaluating a Lazy object means only asking it to return the final value (it doesn't replace itself with the value), so later on it should have used the correct value. Nevertheless, `parse_conf_data` was replacing the Lazy object with its early evaluation value, and that was the main cause of …
> Fix - Template substitution with variable update

- tests_functional/issues/658_nested_envvar_override/Makefile
- tests_functional/issues/658_nested_envvar_override/app_test.py
Just asserting this works on current version.
It was fixed by #795
> Assert #658 works

- dynaconf/base.py
- tests_functional/issues/867_django_lowercase_recursion/manage.py
- tests_functional/issues/867_django_lowercase_recursion/myprj/asgi.py
- tests_functional/issues/867_django_lowercase_recursion/myprj/settings.py
- tests_functional/issues/867_django_lowercase_recursion/myprj/urls.py
- tests_functional/issues/867_django_lowercase_recursion/myprj/wsgi.py
- tests_functional/issues/867_django_lowercase_recursion/settings.toml
This fixes the special case that caused infinite recursion with the option `lowercase_read=False` in #867 .
[This solution](https://github.com/dynaconf/dynaconf/issues/867#issuecomment-1477129966) of some months ago was working at the time, but I misinterpreted the expected behavior for `lowercase_read=False`, which disallows only all lowercase characters (but permits other cases), as shown in those unit test: https://github.com/dynaconf/dynaconf/blob/c43c29e4cf96bb7174d4a582c644dccd1c3d31f0/tests/test_base.py#L47.
The solution consisted in replacing `_store.as_dict()[name]` with a more direct access method, which luckly avoided the recursive calls.
> Fix - Infinite recursions in django app with lowercase_read=False #867

- dynaconf/loaders/redis_loader.py
- dynaconf/loaders/vault_loader.py
The [deprecation warning](https://github.com/dynaconf/dynaconf/issues/950) was quite straighfoward. Only the `kv2.read_secret_version` seems to be involved.
[This](https://github.com/redis/redis-py/issues/1269) explain the redis deprecation warning and this shows that `hmset` can be replaced by `hset`. The use of `hset` here requires `redis` [v4](https://docs.redis.com/latest/rs/release-notes/legacy-release-notes/rlec-4-0-june-2015/) (2015) or higher. Should we add a fallback?
> Update vault and redis APIs as suggested in deprecation warnings. fix #950

- dynaconf/base.py
- dynaconf/loaders/base.py
- dynaconf/loaders/py_loader.py
- tests/test_nested_loading.py
- tests_functional/issues/835_926_enable-merge-equal-false/Makefile
- tests_functional/issues/835_926_enable-merge-equal-false/app_test.py
Fix #835 and #926 
The problem was that `False` was treated as a general fallback and would not be used even if located in a high override-priority position:
* local-scope marks
* file-scope marks
* global-flag
To solve it, I applied the same strategy used in some places of the codebase of using the `empty` sentinel for not-set values, thus making override priority relationships more explicit.
> Fix - Enable merge equal False

- CONTRIBUTING.md
- Makefile
- dynaconf/base.py
- requirements_dev.txt
**problem**: `docker-compose` [from pypi ](https://pypi.org/project/docker-compose/1.29.2/)does not seem maintained (the last release is from 2021). The last version from pypi (`1.29.2`) depends on `pyyaml<=6`, which has a deprecated config that is causing the CI failure.
> CI - Test docker-compose pyyaml issue

- dynaconf/__init__.py
- dynaconf/base.py
- dynaconf/cli.py
- dynaconf/contrib/django_dynaconf_v2.py
- dynaconf/hooking.py
- dynaconf/loaders/__init__.py
- dynaconf/loaders/base.py
- dynaconf/utils/__init__.py
- dynaconf/utils/functional.py
- dynaconf/utils/inspect.py
- dynaconf/utils/parse_conf.py
- tests/test_base.py
- tests/test_hooking.py
- tests/test_inspect.py
- tests_functional/django_example/Makefile
- tests_functional/django_example/foo/a_plugin_folder/dynaconf_hooks.py
- tests_functional/django_example/foo/dynaconf_hooks.py
- tests_functional/django_example/polls/tests.py
- tests_functional/issues/905_item_duplication_in_list/app.py
- tests_functional/issues/969/app.py
This PR allows changing the wrapped class with
a class that allows hooks on specific methods.
This will enable https://github.com/ansible/galaxy_ng/pull/1837
This PR also fixes: #969
This PR replaces #828 
Allows to add AFTER and BEFORE hooks to some dynaconf methods
```python
from dynaconf.hooking import Action, Hook, HookableSettings
settings = Dynaconf(_wrapper_class=HookableSettings)
def lookup_for_key_in_cache_or_database(settings, value,  key, default):
print(f"doing things to lookup key {key!r} on cache or db")
new_value = find_in_cache(key) or query_db(key) or value 
return new_value
settings.register_hook(Action.AFTER_GET, lookup_for_key_in_cache_or_database)
```
Then in any part of code
```python
>>> from config import settings
>>> …
```
> Hooking: Add support for changing the wrapped class

- dynaconf/base.py
Fix https://github.com/dynaconf/dynaconf/issues/984
NOTE: Looks like there is an issue with multithreading
because the state _bypass_evaluation is being mutated on
shared settings obj.
> Hotfix bypass evaluation #984

- docs/advanced.md
- docs/cli.md
- dynaconf/__init__.py
- dynaconf/cli.py
- dynaconf/utils/inspect.py
- tests/test_cli.py
- tests/test_inspect.py
- tests/test_redis.py
- tests/test_vault.py
- tests_functional/custom_loader/app.py
This is a review PR for the Inspect feature #939 
(I'm actively updating this section)
from `inspect_settings(key_dotted_path: str, ...)` to `inspect_settings(key: str, ...)`
from `get_history(key_dotted_path: str, ...)` to `get_history(key: str, ...)`
Justification: Explicit names are usually good, but in the context of Dynaconf `key` is used as dotted-path (as in `setting.get` for example), which makes it more consistent. Also, the docstring makes the usage clear and, if we support other path access (like `foo__bar`), `key` can accommodate that semantic.
from `header.filter.history_order=ascdending | descending`
to `header.chronological_sort=True | False` (more clear information)
The behavior of the history report may be counter-intuitive, specially with merge flag. It kinda snapshots …
> Inspect Review

- setup.py
Dynaconf currently passes raise_on_deleted_version to HVAC's read_secret_version method. This is not supported in HVAC versions before 1.1.0.
Fixes #1009
> Set minimum HVAC version

- dynaconf/base.py
- tests/test_base.py
- tests_functional/issues/1011_env_with_underline/app.py
- tests_functional/issues/1011_env_with_underline/settings.toml
Revert change added in #830, I was not able to find the reason for the change
The env name must allow `_` 
Fix #1011
> fix(env):allow underscore in env name #1011

- docs/envvars.md
Discussion #1017 
I've decided to follow the already existing links style even though `mkdocs` writes messages like this:
```
INFO    -  Doc file 'envvars.md' contains an absolute link '/configuration/#envvar_prefix', it was left as is. Did you mean 'configuration.md#envvar_prefix'?
```
> Fix link to configuration page

- docs/settings_files.md
The example's syntax have a mistake.   At the line end of "root_path" should have a ", "
> [Doc] Fix the syntax errors of  the  doc  programming example.

- docs/flask.md
The link http://flask.pocoo.org/docs/0.12/patterns/subclassing/ leads to a page not found. I replaced it with the current link.
> replace dead link flask subclassing page

- .github/workflows/main.yml
I thought I had fixed this in the last commit about the new release workflow, but apparently not.
> chore(ci): Fix misspelled GitHub action names on main.yml

- dynaconf/base.py
- dynaconf/default_settings.py
Fixed an issue where a portion of variable names was spelled as `mispell` instead of `misspell`.
> chore: Fix misspelled variable name for misspell

- docs/envvars.md
You are describing dot env files in ths section. The env name should be `DYNACONF_USER` rather than `PREFIX_USER`. If not, the program could not read the env correctly.
> [Doc] Fix a small mistake of .env file in the document

- docs/dynamic.md
- dynaconf/base.py
- dynaconf/utils/parse_conf.py
- tests/test_utils.py
Fix #1038
https://deploy-preview-1040--dynaconf.netlify.app/dynamic/#name-aliasing 
In certain cases you need to reuse some variable value respecting the exact 
data type it is previously defined in another step of the settings load.
Example:
`config.py`
```py
settings = Dynaconf(settings_files=["settings.toml", "other.toml"])  
```
`settings.toml`
```toml 
thing = "value"
number = 42
```
`other.toml`
```toml 
other_thing = "@get thing"
other_thing = "@get thing 'default value'"
other_number = "@get number @int"
other_number = "@get number @int 12"
```
The `@get` is lazily evaluated and subject to `DynaconfFormatError` in case of
malformed expression, it is recommended to add validators.
> feat: Add `@get` converter to alias existing keys

- docs/advanced.md
- docs/cli.md
- docs/configuration.md
- docs/django.md
- docs/envvars.md
- docs/faq.md
- docs/flask.md
- docs/index.md
- docs/merging.md
- docs/pt-br/docs/cli.md
- docs/pt-br/docs/flask.md
- docs/pt-br/docs/index.md
- docs/release_notes.md
- docs/secrets.md
- docs/settings_files.md
- docs/validation.md
- mkdocs.yml
Working on a recent PR, the output from `mkdocs build` and `mkdocs serve` was very noisy because of warnings. This PR fixes them all to make the build clean. There were many like the first screenshot.
Much cleaner, only a few warnings around the Portuguese language docs which I wasn't sure how to deal with.
- My IDE automatically deleted some trailing whitespace from the markdown files on save
- I'm not sure if the previous version of the references was actually useful within the Portuguese docs? Can you advise how these are currently in use?
> docs: Fix mkdocs warnings for cleaner build output

- dynaconf/base.py
- tests_functional/issues/1025_include-with-root-path/Makefile
- tests_functional/issues/1025_include-with-root-path/app.py
- tox.ini
The include loader was not handling the relative `root_path` correctly.
Closes #1025
> fix: include load with relative root path

- .github/workflows/main.yml
- .github/workflows/release.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- _typos.toml
- docs/cli.md
- docs/validation.md
- dynaconf/base.py
- dynaconf/cli.py
- dynaconf/loaders/__init__.py
- dynaconf/loaders/base.py
- dynaconf/utils/__init__.py
- dynaconf/utils/parse_conf.py
- requirements_dev.txt
- tests/test_flask.py
- tests/test_inspect.py
- tests/test_utils.py
- tests/test_validators.py
- tests_functional/full_test/app.py
- tests_functional/issues/1000_django_attribute_error/flab/README.md
- tests_functional/validators/with_python/.env
Hey guys, this is optional but I've found this tool to be quite good. It's built in rust so it's fast and I've found it to be pretty accurate. However, in the pre-commit I've put it to warn, rather than write the changes automatically so that the developer has the choice to configure if needed. Let me know if there are other sections that you'd want excluded.
https://github.com/crate-ci/typos/tree/master
```typos```
```typos -w    # Writes the changes```
> Introduce typos pre-commit and fix all current typos

- docs/index.md
The `settings.toml` example for initializing Dynaconf includes an inline table and a separate section that looks like it should nest. However, TOML's inline tables must be entirely self contained, with no members in a separate section.
> fix incorrect combination of TOML table and inline table

- docs/validation.md
The validation sections was providing some wrong information about instantiation trigger.
What this does:
* Adds suggestion presented in #1069 
* Clarifies wrong information pointed by #1068
* Adds "warning" note about possible reason for unexpected validation trigger, like when `pytest` do its test collection in #563.
closes: #1068 #1069
> docs: fix wrong info about validation trigger on instantiation

- .github/workflows/netlify.yml
- netlify.toml
What this does:
- Add workflow to publish docs to netlify through [Netlify GitHub action](https://github.com/marketplace/actions/netlify-actions#usage) (instead of using the Netlify App)
- The workflow is triggered on semver tags and through workflow dispatch.
- The manual dispatch provides an option to checkout to another refspec before building the docs (in the case a building an on-tag build failed for some reason).
- Comment out the `netlify.toml` build definitions, so the App won't interfere with Github actions.
> chore(ci): Add workflow to publish docs to netlify

- docs/validation.md
- dynaconf/validator.py
- tests_functional/issues/1055_double_cast_validator/app.py
```python
from dynaconf import Validator
settings = Dynaconf(var="dynaconf")
def a(v):
print("called a, replace conf -> settings")
return v.replace("conf", "settings")
def b(v):
print("called b, transform to upper DYNASETTINGS")
return v.upper()
validators = [
Validator("var", cast=a),
Validator("var", cast=b),
]
settings.validators.register(*validators)
settings.validators.validate_all()
assert settings.var == "DYNASETTINGS", settings.var
```
Fix #1055
> Fix #1055 allow multiple validators with cast for the same field

- docs/cli.md
- dynaconf/cli.py
- dynaconf/utils/__init__.py
- tests/config.py
- tests/test_cli.py
- tests/test_utils.py
Problem: `dynaconf list` is formatted and cannot be processed by JSON tools in terminal.
stdout can't be piped to a file `> settings.json` or processed by tools such as `jq` 
Current output on `$ cd dynaconf/tests_functional/full_example`
```console
$ dynaconf -i app.settings list                        
Working in development environment 
LOAD_DOTENV<bool> True
DEFAULT_SETTINGS_PATHS<list> ['settings.py',
'settings.toml',
'settings.tml',
'settings.yaml',
'settings.yml',
'settings.ini',
'settings.conf',
'settings.properties',
'settings.json',
'.secrets.py',
'.secrets.toml',
'.secrets.tml',
'.secrets.yaml',
'.secrets.yml',
'.secrets.ini',
'.secrets.conf',
'.secrets.properties',
'.secrets.json']
WORKS<str> 'full_example'
HOSTNAME<str> 'host.com'
PORT<int> 5000
VALUE<float> 42.1
ALIST<list> …
```
> feat: dynaconf list with `--json` will print valid JSON to stdout

- dynaconf/typed.py
- tests/test_typed.py
closes #1104
We can release as a Tech Preview as it is a non-breaking feature
```python
from typing import Annotated
from dynaconf.typed import Dynaconf, Validator, Options
class Settings(Dynaconf):
dynaconf_options = Options(
envvar_prefix="MYAPP", 
settings_file="settings.yaml",
)
host: str = "server.com"
port: Annotated[int, Validator(gt=999)]
validate_ssl: bool = True
settings = Settings(port=1080)
assert settings.HOST == "server.com"
assert settings.port >= 999
assert settings.get("validate_SSL") is True
```
> feat: Typed Settings

- docs/flask.md
- dynaconf/base.py
- dynaconf/contrib/flask_dynaconf.py
- dynaconf/utils/parse_conf.py
- tests/test_flask.py
fix #1113
Dynaconf transform nested data structures to a new DynaBox instance, this is an
object that allows dot notation access such as `app.config.key.value.other`.
However this feature is imcompatible with some Flask extensions, for example:
`Flask-Alembic`.
So in case you see a `BoxKeyError` when running your app with you can run it on
compatibility mode.
```python
FlaskDynaconf(app, compatibility_mode=True)
```
The downside is that now you cannot access nested elements using dot notation
but the usual access interface via dict subscription will work normally:
`app.config["KEY"]["value"]["other"]`
!!! info
On Dynaconf 4.0 compatibility_mode will default to True when running
on Flask.
> fix(flask):Allow disabling transformation of dict to Dynabox

- dynaconf/typed/__init__.py
```console
dynaconf/typed/__init__.py:25
/home/rochacbruno/Projects/dynaconf/dynaconf/typed/__init__.py:3: UserWarning: dynaconf.typed
module is on tech preview stage. The feature will be fully supported on dynaconf>=4.0.0. The
feature works and is heavily tested however the APIs and usage are subject to change.
warnings.warn(
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
> misc:add warning about typed being tech-preview

- dynaconf/typed/__init__.py
- dynaconf/typed/types.py
- dynaconf/typed/validators.py
- dynaconf/validator_conditions.py
- tests/test_typed.py
- tests_functional/typed/typed_with_dotenv_toml_secrets_validator_condition/app.py
- tests_functional/typed/typed_with_dotenv_toml_secrets_validator_condition/config.py
- tests_functional/typed/typed_with_dotenv_toml_secrets_validator_condition/settings.toml
Inspired by the module https://github.com/annotated-types/annotated-types added some better named validators.
Also reorganized validation objects under typed/validators.py
```python
from typing import Annotated
from dynaconf.typed import Dynaconf
from dynaconf.typed.validators import Eq, Contains, IsUrl, Regex, Not
class Settings(Dynaconf):
fruit: Annotated[str, Not(Eq("banana"))]
static_url: Annotated[str, IsUrl()]
version: Annotated[str, Regex(r"^(\d+).(\d+).(\d+)$")]
colors: Annotated[list[str], Contains("red")]
```
all the above are just aliases, which is equivalent to
```python
from typing import Annotated
from dynaconf.typed import Dynaconf, Validator
class Settings(Dynaconf):
fruit: Annotated[str, Validator(ne="banana"))]
static_url: Annotated[str, …
```
> Validators aliases

- docs/dynamic.md
- tests_functional/legacy/hooking/app.py
fix #1095
feature added on 3.2.2 https://github.com/dynaconf/dynaconf/releases/tag/3.2.2
Dynaconf can be configured to retrieve a special variable from an external
storage such as GCP or AWS secrets or a Vault server or even a secret located
on the filesystem or encrypted.
This works by registering a function hook that will be called for every variable
access on Dynaconf.
This feature is useful to load settings from BitWarden and other secret managers.
NOTES:
- You must define the logic of each hook, dynaconf just calls it
- You must take care of caching and caching invalidation
- This may introduce overhead dependending on how the hook function is
implemented
```python
CACHE = {}  # could be Redis
def get_data_from_somewhere(settings, result, key, *args, **kwargs):
"""Your function that …
```
> docs(hook):Add documentation and example of Access Hooks

- docs/django.md
Closes #648
The issue #648 is currently **impossible** to fix, it is a trede-off of patching the django settings, as our plan for 4.0 is to deprecate Django patching in favour of a more explicit way to attach dynaconf to Django, I condider that issue closed and improved the django docs.
Closes #578 
Added Pylint issue to known caveats
> docs(django):Improve Django Docs, make explicit mode the recommended.

- dynaconf/base.py
- dynaconf/hooking.py
- dynaconf/utils/boxing.py
Aplied the same fix of 3.2.6 to avoid overhead on access hooks.
Summary:
With a `function` as `_registered_hooks` every time a key is accessed on `settings`
the `function` is invoked passing a `settings` object as first argument.
BEFORE:
The `settings` passed to the hook was instantiated for every call.
AFTER:
The `settings` is now a `TempSettingsHolder` that has no effect on passing
and is instantiated only if accessed.
Saved execution time from 0m49 to 0m3 on a Django openapi spec view.
> fix(hooks):Improve performance of Access Hooks

- dynaconf/utils/functional.py
- dynaconf/vendor/box/box.py
- requirements_dev.txt
- tests/test_base.py
- tests/test_redis.py
- tests/test_vault.py
Closes #1042 
Notes:
* The first level is always uppercase internally and calling del with different case attr-name would fail.
* Currently we only support deleting a nested level item with exact matching (not sure if needs "fixing").
> fix: del attr wouldnt work with lowercase

- docs/flask.md
- dynaconf/utils/inspect.py
- tests/test_inspect.py
get_history() should provide the original representation, so the user can reliably inspect its data.
The evaluted value might be hard to track and potentially confusing to inspect.
Closes #1180
> [!NOTE]
> This should be backported to the 3.2.6 stream branch so it can be released before 3.3.0
> Fix get_history behavior regarding lazy values

- dynaconf/base.py
- tests/test_base.py
Add support for deleting items by keyword, by
adding the __delitem__ method to the Settings
class.
This way, users may delete items by doing:
```
del settings["my_key"]
```
As a counterpart to delete only by attribute.
> Implement `__delitem__` method for base Settings

- dynaconf/contrib/django_dynaconf_v2.py
- dynaconf/validator.py
- Combined Validators was failing with `tuple object has no attr get` because those were using superclass `repr`, implemented a custom repr that combined repr from every validator.
- Replaced use of __dict__ with inspect.getmembers as the use of `__dict__` is not recommended anymore.
> fix: Implement repr for combined validators

- dynaconf/utils/parse_conf.py
- tests/test_base.py
> fix: using merge with comma separated values will infer type [port from 3.2.8]

- tests/test_loaders.py
Looks like we already raise an error on syntax errors.
> fix: Ensure an error is raised when loading files with syntax errors

- docs/advanced.md
- dynaconf/__init__.py
- dynaconf/base.py
- dynaconf/hooking.py
- dynaconf/loaders/__init__.py
- dynaconf/loaders/py_loader.py
- tests/test_py_loader.py
Related to #1245
To be ported to master branch after merge
**new in 3.2.8**
When the settings file is a Python file, you can also use a decorator to define hooks.
```python
settings = Dynaconf(settings_file="settings.py")
```
`settings.py`
```python
from dynaconf import post_hook
VARIABLE = "value"
...
@post_hook
def set_debugging_database_url(settings):
data = {}
if settings.DEBUG:
data["DATABASE_URL"] = "sqlite://"
return data
```
Dynaconf will collect the decorated functions and execute them after the settings file is loaded.
> feat: Add support for decorated hooks on settings files

- dynaconf/hooking.py
- dynaconf/loaders/py_loader.py
- tests_functional/django_example/foo/a_plugin_folder/settings.py
Using getattr during load on a value would trigger eager evaluation, changed to use name instead.
> fix: Hotfix hook collector to avoid eager evaluation.

- dynaconf/hooking.py
- dynaconf/loaders/py_loader.py
- tests_functional/legacy/django_example/foo/a_plugin_folder/settings.py
Using getattr during load on a value would trigger eager evaluation, changed to use name instead.
> fix: Hotfix hook collector to avoid eager evaluation. (#1255) [port from 3.2.10]

- docs/secrets.md
It may not be clear that the example redis hash name provided [here](https://www.dynaconf.com/secrets/?h=redis#using-redis:~:text=You%20can%20now%20write%20variables%20direct%20in%20to%20a%20redis%20hash%20named%20DYNACONF_%3C%20env%20%3E%20for%20example%3A) only reflects the default `ENVVAR_PREFIX_FOR_DYNACONF`.  
This PR clarifies that when using environments, the Redis hash name would be `< ENVVAR_PREFIX_FOR_DYNACONF >_< env >` rather than the default `DYNACONF_< env >`. 
A small technicality but it might save some troubleshooting for those using custom environments. 
- [Usage in redis_loader](https://github.com/dynaconf/dynaconf/blob/2f9a15500f3f254a69eb1a7485387c6e1f259731/dynaconf/loaders/redis_loader.py#L93)
---
Backported from: https://github.com/dynaconf/dynaconf/pull/1266 …
> docs: clarification on redis hash title when using custom envvar prefix (backport/3.2)

- .github/actions/install-from-wheel/action.yml
- .github/workflows/main.yml
- Makefile
- minify.sh
- pyproject.toml
- tests_functional/issues/685_disable_dotted_lookup/app.py
This PR:
* Adds missing build/release dependencies: `python-minifier` and `build`.
* Makes CI use (as installation source) the distribution wheel we expect to release
* Adds check to the `minify.sh` script to ensure we are using our lowerbound python, as it may create incompatible changes to the vendored code otherwise. (as reported by Bruno!)
> Run CI test against distribution wheel

- dynaconf/nodes.py
- dynaconf/utils/__init__.py
- pyproject.toml
- scripts/timing_compare.py
- tests/test_nodes.py
Replaces https://github.com/dynaconf/dynaconf/pull/1306
Experimenting with the plan [here](https://github.com/dynaconf/dynaconf/issues/1298#issuecomment-3046242845).
Taking https://github.com/dynaconf/dynaconf/pull/1162/ in consideration.
This first part should ensure the new implementation complies with most Box usage, without yet replacing it.
Also, it should add some unit test hardening to the desired behavior of those classes.
Summary:
> [PULP-647] Add and test alternative Box (#1298/part 1)
