docs/guides/usage.md

This library is great, just a correction in the docs.
There must be AT LEAST one default section.
Changed **ATTENTION** to **ATTENTION**: to match with the style of **NOTE:**

small corrections for usage.md

---

Makefile
dynaconf/loaders/__init__.py
dynaconf/loaders/base.py
dynaconf/loaders/py_loader.py
dynaconf/utils/files.py
example/project_root/.env
example/project_root/app.py

Added example/project_root and entry on Makefile:test_examples

Fix #106 make PROJECT_ROOT_FOR_DYNACONF to work with custom paths

---

docs/guides/usage.md

Fix #110 add docs for dynaconf_include

---

Makefile
azure-pipelines.yml
dynaconf/utils/__init__.py
dynaconf/utils/files.py
example/issues/160/.env
example/issues/160/subfolder/.keep
example/issues/160/test.sh

Search should stop at breaking point  only if ROOT_PATH is defined

fix #160 - invoking directory should not be search breaking point.

---

dynaconf/base.py
dynaconf/contrib/flask_dynaconf.py
dynaconf/loaders/base.py
dynaconf/loaders/vault_loader.py
tests/test_envvar_prefix.py

Fix  base loader when having no ENVVAR_PREFIX_ (Addresses #177)

---

dynaconf/loaders/vault_loader.py

Using the old `read` and `write` methods in `hvac` caused inconsistent reading and writing to Vault. Using the Key/Value API solves the inconsistencies.

Use the Key Value API rather than the old 'read' and 'write' methods

---

docs/guides/advanced_usage.md
docs/guides/cli.md
dynaconf/cli.py
dynaconf/loaders/__init__.py

fix #200
```bash
dynaconf list -o path/to/file.yaml --output-flat
```

Add support to export merged env to filesystem via cli.

---

dynaconf/base.py
dynaconf/loaders/vault_loader.py
example/vault/vault_example.py

Addresses Issue #211 
This also removes restriction placed on `env` name to not include `_` characters.

Adding new feature to address issue #211

---

dynaconf/base.py

Addresses issue discussed in #237

Fixing how filename.local.* files are loaded

---

docs/guides/advanced_usage.md
docs/guides/configuration.md
docs/guides/usage.md
dynaconf/loaders/__init__.py
dynaconf/utils/__init__.py
dynaconf/utils/files.py
tests/test_utils.py
tests/test_yaml_loader.py

also MERGE_ENABLED is no more deprecated.

Fix #236 added .local. files loading and module impersonation docs

---

dynaconf/cli.py
dynaconf/validator.py
example/validators/with_toml/dynaconf_validators.toml
tests/conftest.py
tests/test_validators.py

Fix #258 
Add support for custom messages to validators.
Implemented in Live https://www.youtube.com/watch?v=XMUIeXNaBpA (pt-BR)

Add custom message to validators

---

dynaconf/utils/__init__.py
tests/test_utils.py

PR recreated #286 to fix some styling issues before merging
fix #285

fix object_merge issue #285 with  meta value

---

dynaconf/cli.py

Changed the code to show the data type and the content of the envvar
Close #304

Changed CLI list to show data type of the envvars to fix #304

---

docs/guides/configuration.md
dynaconf/base.py
dynaconf/default_settings.py
dynaconf/loaders/json_loader.py
dynaconf/loaders/yaml_loader.py
dynaconf/utils/__init__.py
dynaconf/utils/parse_conf.py
tests/test_json_loader.py
tests/test_utils.py

Fix #305 - printing and exporting LazyFormat

---

.gitignore
docs/guides/contribute.md

I had problems to start to contribute on this project.
**I forgot to install the pre-commit :( !!**
So I created this little steps to help futures contributor.

Added little information about how dev into this project.

---

Makefile
docs/guides/configuration.md
docs/guides/usage.md
dynaconf/base.py
dynaconf/cli.py
dynaconf/default_settings.py
dynaconf/loaders/base.py
dynaconf/loaders/py_loader.py
dynaconf/loaders/vault_loader.py
example/envless_mode/app.py
example/envless_mode/settings.yaml
tests/test_base.py

Passing `ENVLESS_MODE_FOR_DYNACONF=True` will make Dynaconf to read all
data from source files without env separation.

Add ENVLESS_MODE option

---

dynaconf/base.py
dynaconf/utils/boxing.py
tests/test_base.py

Fix #298 allow auto complete for editors and console
implemented `__dir__` on Settings and Dynabox

Fix #298 auto complete

---

Makefile
dynaconf/base.py
dynaconf/cli.py
dynaconf/default_settings.py
dynaconf/loaders/__init__.py
dynaconf/loaders/env_loader.py
dynaconf/loaders/redis_loader.py
dynaconf/loaders/vault_loader.py
dynaconf/utils/boxing.py
dynaconf/utils/parse_conf.py
dynaconf/vendor/box/box.py
example/issues/359_variable_reference/app.py
example/issues/359_variable_reference/settings.yaml
tests/test_dynabox.py
tests/test_utils.py

fix #359 lazy templates on nested keys

fix #359 lazy templates on nested keys

---

docs/flask.md
dynaconf/contrib/flask_dynaconf.py
dynaconf/utils/parse_conf.py
example/issues/323_DEFAULT_VALUES_RESOLUTION/app.py
example/issues/323_DEFAULT_VALUES_RESOLUTION/settings.toml
example/issues/325_flask_dot_env/.env
example/issues/325_flask_dot_env/app.py
example/issues/327_flask_extensions_warning/app.py
example/issues/327_flask_extensions_warning/settings.toml
example/issues/341_box_it_up/app.py
example/issues/341_box_it_up/settings.yaml
tests/test_flask.py

Fix #323
Fix #325
Fix #327
Fix #341
Exemples added:
example/issues/323_DEFAULT_VALUES_RESOLUTION/
example/issues/325_flask_dot_env/
example/issues/327_flask_extensions_warning/
example/issues/341_box_it_up/

Flask and other fixes

---

docs/index.md
dynaconf/base.py
example/issues/379_dict_like_iteration/app.py
example/issues/379_dict_like_iteration/settings.toml
tests/test_base.py

Fix #379 dict like iteration

---

docs/index.md

Fix #388 URL reference for custom loaders

Fix #388 URL reference for custom loaders

---

.gitignore
dynaconf/base.py
example/django_example/foo/settings.py
example/django_example/foo/urls.py
example/django_example/polls/tests.py
example/django_example/settings.yaml
requirements_dev.txt
tests/test_django.py

Fix #382 add is_overriden method
Fix #382 add is_overriden method for DJDT

Fix #382 add DJDT method

---

Makefile
azure-pipelines.yml
dynaconf/base.py
dynaconf/utils/__init__.py
dynaconf/utils/boxing.py
dynaconf/utils/parse_conf.py
example/issues/392_evaluate_nested_structures/app.py
example/issues/392_evaluate_nested_structures/issue.md
example/issues/392_evaluate_nested_structures/settings.toml
example/issues/392_evaluate_nested_structures/settings.yaml
tests/test_validators.py

Allow nested Lazy Values …
Fix #392
Fix #402

Allow nested Lazy Values

---

dynaconf/cli.py

Fix #399 - Update documentation link

---

docs/release_notes.md

Just a small typo that made my sleepy brain confused.

Fix typo in release notes

---

Makefile
dynaconf/base.py
dynaconf/utils/__init__.py
example/issues/253_set/app.py
example/issues/384_dotted_set/README.md
example/issues/384_dotted_set/app.py
tests/test_base.py

Fix #384 and other merge problems
```py
settings.set("a.b", {"other": 1, "dynaconf_merge": True})
settings.set("a.b", {"dynaconf_merge": {"another": 2}})
settings.set("a.b", "@merge {foo='bar'}", tomlfy=True)
```

384 fix tail and dotted merge

---

dynaconf/loaders/base.py
tests/test_yaml_loader.py

Fix #432 no more warning on missing envs

Fix #432 no more env warning

---

example/issues/284_local_sets/app.py
example/issues/284_local_sets/settings.local.toml
example/issues/284_local_sets/settings.toml

Close #284 
is not a bug but a missing of explicit merge tokens

Close #284 not a bug

---

docs/configuration.md

Changed the merging hyperlink in sections _merged_enable_ and _nested_separator_

fix merging hyperlink to fix  #454

---

docs/index.md
dynaconf/cli.py
dynaconf/loaders/env_loader.py
example/dummy_flask_extension/__init__.py
tests/test_flask.py

Fix docs regarding --django argument on cli

---

dynaconf/loaders/vault_loader.py
tests/test_vault.py

Read secrets from Vault kv v2 regarding the current environment. (#483)

Fix reading secret from Vault kv v2 (#483)

---

dynaconf/contrib/flask_dynaconf.py
example/flask_with_dotenv/app.py
example/issues/194_flask_config/app.py
requirements_dev.txt
tests/test_base.py
tests/test_flask.py

Fix #521 - FlaskDynaconf should raise KeyError for non existing keys

---

Makefile
dynaconf/utils/boxing.py
example/issues/486_title_case_validation/app.py
example/issues/486_title_case_validation/settings.yaml

Allow Title case lookup and validation.

---

Makefile
dynaconf/base.py
dynaconf/utils/parse_conf.py
example/issues/482_layered_format/app.py
example/issues/482_layered_format/other.toml
example/issues/482_layered_format/settings.toml

Fix #482 - formatter case insensitive

---

tests/test_base.py

I can't reproduce the bug #492 but I added a test to ensure.

Added a test to reproduce #492 (not able to reproduce)

---

dynaconf/base.py

Fix #511
```py
settings.execute_loaders(loaders=[dynaconf.loaders.env_loader])
```

Fix #511 allow user to specify loaders argument to execute_loaders

---

dynaconf/vendor/box/box_list.py
dynaconf/vendor/ruamel/yaml/compat.py
dynaconf/vendor/ruamel/yaml/resolver.py
dynaconf/vendor_src/box/box_list.py
tests/test_dynabox.py

Fix #462 make DynaBox nested List to use DynaBox as default class

---

dynaconf/contrib/flask_dynaconf.py
tests/test_flask.py

Flask still missing __contains__

HOTFIX for 501

---

dynaconf/utils/__init__.py
dynaconf/utils/parse_conf.py
tests/test_dynabox.py
tests/test_flask.py
tests/test_utils.py

NamedTuple not parsed as BoxList fix #595

---

dynaconf/utils/files.py
tests/test_django.py
tests/test_utils.py

Do not search anywhere if the absolute path to a file provided

---

docs/advanced.md
dynaconf/base.py
dynaconf/loaders/__init__.py
dynaconf/loaders/base.py
dynaconf/loaders/py_loader.py
dynaconf/utils/__init__.py
example/django_example/.env
example/django_example/foo/a_plugin_folder/dynaconf_hooks.py
example/django_example/foo/a_plugin_folder/settings.py
example/django_example/foo/settings.py
example/django_example/polls/tests.py
tests/test_py_loader.py

Fix #654
Allow dynaconf_hooks to be executed on post load

Add support for dynaconf_hooks(post) issue #654

---

docs/advanced.md
docs/validation.md
setup.py

Add missing docs and missing python_requires

---

dynaconf/loaders/vault_loader.py

Fix #768 of kv property depreciation from client object

---

docs/envvars.md

"According to 12factorapp is is" ---> "According to 12factorapp it is"

envars.md typo fix

---

docs/pt-br/docs/cli.md
docs/pt-br/docs/index.md

This is a first version in PT-BR of Dynaconf Documentation.
At the moment was translated index.md and cli.md

docs(pt-br): Docs Translation to brazilian portugues.

---

dynaconf/loaders/vault_loader.py

Fix #807 Use client.auth.approle.login instead of client.auth_approle

---

.coveragerc
docs/index.md
dynaconf/utils/__init__.py
tests/test_yaml_loader.py
tests_functional/issues/814_spaces_in_keys/app.py
tests_functional/issues/814_spaces_in_keys/settings.yaml

[bugfix] Fix access of keys with spaces

---

.github/workflows/main.yml
dynaconf/base.py
setup.py
tests/test_base.py

Add Python 3.11 to CI

---

docs/pt-br/docs/flask.md

In 2023 I would like to contribute to the open-source community. I don't have much experience in the area but we need to start with something, which is a small contribution to a project maintained by a guy that I think is really cool (@rochacbruno). 
I would greatly appreciate your feedback.

doc(pt-br): translate flask extension to pt-br

---

.github/workflows/doc-ignore.yml

fix #885 (initial) and #886 (test PR)

CI - Prevent running when just doc changes are made (fix)

---

docs/configuration.md

Some minor modifications are out of the main scope of the PR (not design changes):
- in **apply_default_on_none** - It didn't have the type/default declarexplicitlytly. Have a look if the inference is correct.
- in **envvar** and **settings_files** - changes as proposed in #884

Docs - Change design of Available Options

---

docs/faq.md
docs/validation.md

About typos, I was reading the Validators docs and found one typo. Then I decided to use Grammarly to check for other things (which I wouldn't catch ever).

Add FAQ questions and small typos on Validation

---

docs/faq.md
docs/settings_files.md

- Add faq about #859 
- Clarify settings file, includes and preload loading strategy #832 #812
- Typos and styles

Docs - Add question to faq and clarify settings loading

---

docs/index.md

Docs - Add `Extensions` header to index and `pytest-dynaconf` reference

---

docs/configuration.md

Docs - Add clarification on DEFAULT_ENV_FOR_DYNACONF config

---

docs/validation.md

The doc has ValidationError being in dynaconf.validators not dynaconf.validator

Update validation.md to fix typo

---

dynaconf/base.py
tests/test_base.py

Fix: unexpected _bypass_evaluation in BoxList

---

dynaconf/base.py
dynaconf/loaders/__init__.py
dynaconf/utils/files.py
tests_functional/issues/982_wildcard/.config/data_sources.yaml
tests_functional/issues/982_wildcard/app.py
tests_functional/issues/982_wildcard/settings.toml
tests_functional/skipfile.toml

Settings_files was not supporting globs
Fix #982

Fix #982 glob on settings_files

---

dynaconf/utils/__init__.py
dynaconf/utils/inspect.py

fix: pep8 errors

---

tests_functional/django_pytest_pure/requirements.txt

Fix: https://github.com/dynaconf/dynaconf/security/dependabot/21

fix: dependabot alert 21 about Django

---

dynaconf/contrib/django_dynaconf_v2.py
tests_functional/django_example/foo/settings.py
tests_functional/django_example/polls/tests.py
tests_functional/django_example/settings.yaml
tests_functional/django_pure/foo/settings.py
tests_functional/django_pure/settings.yaml

fix(django): Add Django transformation of STATIC_URL

---

dynaconf/loaders/__init__.py

fix(hooks): Ignore if file doesn't exist

---

dynaconf/utils/inspect.py
tests/test_inspect.py

This fixes the error by avoiding the attempt to evaluate altogheter.
get_history() should provide the original representation, so the user can reliably inspect its data. The evaluted value might be hard to track and potentially confusing to inspect.
Backported from master: b23dac4
Closes #1180
> [!NOTE]
> I'm using the `stream_3.2.6` branch here as it if was a `3.2.z` branch, since we already have 3.3 stuff on master.

[backport] fix(inspect): Fixed an error that would raise when using get_history with lazy values

---

dynaconf/utils/parse_conf.py
dynaconf/validator.py
tests_functional/issues/1196-early-trigger-on-validation/app.py

fix: lazy validator default value would evalute early

---

dynaconf/utils/parse_conf.py
dynaconf/validator.py
tests_functional/issues/1196-early-trigger-on-validation/app.py

Backporting if we want to release this in 3.2.7, before 3.3.0
fixes: #1196

[Backport 3.2] Fix early trigger of lazy value

---

docs/advanced.md
dynaconf/__init__.py
dynaconf/base.py
dynaconf/hooking.py
dynaconf/loaders/__init__.py
dynaconf/loaders/py_loader.py
tests/test_py_loader.py

* feat: Add support for decorated hooks on settings files
Closes #1245
Port of #1246

[port from 3.2.8] feat: Add support for decorated hooks on settings files (#1246)

---

.github/workflows/main.yml
.github/workflows/test.yml
minify.sh
pyproject.toml

Closes https://github.com/dynaconf/dynaconf/issues/1259

chore(packaging): Update python versions usage on metadata and CI

---

dynaconf/utils/boxing.py

https://github.com/dynaconf/dynaconf/blob/stream_3.2.6/dynaconf/vendor/box/box.py#L285-L290

Make raw variables private
